export enum TConnectors {
  // AUTHEREUM = "AUTHEREUM",
  // FORMATIC = "FORMATIC",
  // LEDGER = "LEDGER",
  INJECTED = "INJECTED",
  // PORTIS = "PORTIS",
  // TORUS = "TORUS",
  // TREZOR = "TREZOR",
  WALLETCONNECT = "WALLETCONNECT",
}
